var userName = "Areeba Ahmed khan";
console.log(userName);
var age = 21;
console.log(age);
var a = "pakistan";
var b = 10.9;
var c = false;
var m = "USA";
var n = 10;
var o = false;
console.log(a);
console.log(b);
console.log(c);
var currentbalance = 1000;
var accountnumber = 123456789;
var firstname = "Muhammad waseem";
var lastname = " rasool";
var fullname = firstname + lastname;
console.log(fullname);
